name: personal_website
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.1
  intl: ^0.16.0
  flutter_html: ^0.11.0
  markdown: ^2.1.1
  zefyr: ^0.8.0
  fb_auth: ^0.0.2+1
  universal_html: ^1.1.6
  firebase: ^5.0.4
  cloud_firestore: ^0.12.9+4
  file_picker: ^1.4.2
  image_picker: ^0.6.1+4
  firebase_storage: ^3.0.6
  clipboard_manager: ^0.0.4
  clippy: ^1.0.0
  flutter_logger: ^0.0.6
  flutter_colorpicker: ^0.2.6
  extended_text: ^0.6.6
  extended_text_field: ^0.4.4
  share: ^0.6.2+1
  tonic: ^0.2.3
  parallax_image: ^0.3.1+1
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_html:
    git:
      url: https://github.com/AppleEducate/flutter_html

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700
  assets:
    - assets/pages/
    - assets/images/
    # assets-generator-begin
    # assets/images/*
    - assets/images/.DS_Store
    - assets/images/app_store.png
    - assets/images/favicon.ico
    - assets/images/google_play.png
    - assets/images/welcome.jpeg
    # assets-generator-end
    - assets/posts/
    - assets/images/apps/the_pitch_pipe/
    - assets/images/apps/the_pocket_piano/
