name: CI

on: [push]

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter build web
      - run: firebase deploy --token "$FIREBASE_TOKEN"
